graph TD


Init_CopyData-->Init_Chars


Init_Chars<-->Init_ScreenPointerArray

Init_Restart<-->Menu_DisplayJMPresents

Init_Restart-->InitLevel_InitialisePlayerStats

Init_ScreenPointerArray-->Menu_DisplayHeader 
Screen_Plot<-->Screen_GetPointer

1190<-->Screen_GetPointer


Game_MoveLandscape-->Screen_DisplayLandscape

Game_MoveLandscape-->Screen_DisplayLandscape

Player_UpdateShipPosition-->.ExitUpdateShipPosition

Player_UpdateShipPosition-->.CheckShipSpeed

Game_DecreaseShipSpeedCounter-->Camel_CheckMarkerUpdate





Player_SetShipSpeed-->.SetShipSpeed


Input_CheckJoyLeftRight-->Input_JoyLeftRight

Input_CheckJoyLeftRight-->Player_SetShipSpeed

Player_ChangeDirection-->.ExitChangeDirection

Player_ChangeDirection-->Player_UpdateShipOffset

Player_TurnShip-->.CheckTurnOffset

Player_TurnShip-->.DecreaseOffset ;Input_CheckJoyLeftRight

Player_UpdateShipState-->Player_TurnShip

Player_UpdateShipOffset-->Player_UpdateShipState



Screen_UpdateCamelMarker-->Screen_MoveMarkerRight



13DA<-->$139A

13DA-->$119A

Screen_MoveMarkerRight-->.SetMarkerSpriteX ;DONE


InitLevel_InitSprites<-->Screen_DisplayLandscape

InitLevel_InitSprites<-->Screen_DisplayGround

InitLevel_InitSprites<-->Screen_UpdateCamelMarker

InitLevel_InitSprites-->InitLevel_InitialseGameVariables


Game_MainLoop<-->Player_UpdateShipPosition

Game_MainLoop<-->Input_CheckInput

Game_MainLoop<-->Game_DecrementTimer

Game_MainLoop<-->Input_CheckJoyLeftRight

Game_MainLoop<-->Player_ChangeDirection

Game_MainLoop<-->Camel_UpdateSprites

Game_MainLoop<-->Camel_Move

Game_MainLoop<-->Input_CheckJoyFire

Game_MainLoop<-->Screen_DecreaseTwinkleCounter

Game_MainLoop<-->Camel_Dying

Game_MainLoop<-->Camel_UpdateCamelHeadFrame

Game_MainLoop<-->Camel_UpdateSpit

Game_MainLoop<-->Player_DamageScreenFlash

Game_MainLoop<-->Game_UpdateCollisionRegister

Game_MainLoop<-->Player_CamelCollisionDetection

Game_MainLoop<-->Game_CheckSectorDefences

Game_MainLoop<-->Game_CheckPause

Game_MainLoop-->Game_MainLoop

Player_DisableExplosionSprites-->Player_ExplosionEnded


Camel_UpdateSprites-->.UpdateCamelRear


Camel_UpdateMarker<-->Camel_MoveMarker

Camel_UpdateMarker-->Player_UpdateLandPosition



1755-->$16A4

IRQ_MoveCamelBackLegs<-->IRQ_FlashPlayerScore

IRQ_MoveCamelBackLegs-->IRQ_GetCamelHeadFrame

IRQ_MoveCamelBackLegs-->IRQ_CheckCamelFrameSound

IRQ_ResetCamelAnimationFrame<-->IRQ_SetCamelHeadFrame

Camel_Move<-->Game_ResetCamelSpeedCounter

Camel_Move<-->.MoveCamelMarker

Camel_Move-->Camel_CheckLandPosition

Camel_Move<-->Camel_FetchMarkerPosition

Camel_Move<-->Screen_Plot

Camel_Move<-->Screen_Plot

17EE-->$16F8

17EE-->$16F6

Input_CheckJoyFire-->Bullet_RedundantRoutine

Bullet_SetDirection<-->Bullet_SetBulletY

Bullet_MoveBullet-->.SetBulletX

Bullet_MoveBullet-->.SetBulletY

Bullet_MoveBullet<-->$24E6 

Bullet_MoveBullet<-->Bullet_ChangeSoundFrequency

Bullet_MoveBullet<-->Score_Add1Point

Bullet_MoveBullet<-->Bullet_HitSound

Bullet_MoveBullet-->Bullet_Disable

Screen_DecreaseTwinkleCounter-->Screen_SelectStarToTwinkle


Bullet_HitSound<-->Bullet_ClearCollisionRegister



Bullet_SetBulletX-->Bullet_SetDirection

Camel_DecreaseCamelHealth<-->Score_AddBonusPoints

Camel_Dying<-->Camel_SetInactive

Camel_Dying<-->Screen_Plot

Camel_Dying-->Camel_CheckRemainingCamels

1982-->$16DF

Camel_FetchMarkerPosition<-->Camel_CheckActive

Camel_FetchMarkerPosition<-->PLA

Camel_FetchMarkerPosition-->.SelectNextCamelToMove



Player_UpdateLandPosition-->.ExitUpdateLandPosition

Player_UpdateLandPosition-->Camel_CheckLandPositionDelay

Camel_MoveMarker<-->Game_MoveLandscape

Camel_MoveMarker-->.ExitMoveMarker

Camel_CheckLandPosition-->Camel_TurnOffSprites

Camel_CheckLandPosition<-->Camel_CheckCamelID

Camel_CheckLandPositionDelay-->Camel_CheckLandPosition


Camel_CheckCamelID-->Camel_CheckCamelPositionMajor

Camel_CheckCamelID<-->PLA 

Camel_CheckCamelID-->.NoCamelInRange




IRQ_Main-->krnINTERRUPT

IRQ_Main<-->IRQ_MoveCamelBackLegs ;DONE

IRQ_Main-->krnINTERRUPT



Camel_CheckCamelPositionMajor-->Camel_CheckCurrentCamelHealth

Camel_CheckCamelPositionMajor-->.NoCamelInRange

Screen_DisplayStars<-->Screen_Plot

Screen_TwinkleStars<-->Screen_Plot

Screen_TwinkleStars<-->Screen_Plot

Screen_TwinkleStars-->Bullet_MoveBullet

Screen_SelectStarToTwinkle<-->Screen_DecreaseCounter

Screen_SelectStarToTwinkle-->Bullet_MoveBullet

Screen_SelectStarToTwinkle-->Screen_TwinkleStars

Bullet_RedundantRoutine-->Bullet_SetBulletX




Camel_UpdateSpit-->Camel_SetSpitFrequency

Camel_SetSpitPosition<-->Camel_TestShipSpitXMatch

Camel_SetSpitPosition-->.SetSpitActive

Camel_SetSpitPosition-->.SetCamelSpitDirection

Camel_SetSpitPosition-->Camel_EnableSpitSprite

Camel_MoveSpit-->.Here ;extraneous

Camel_MoveSpit-->.UpdateSpitY

Camel_MoveSpit-->Camel_DisableSpitSprite

Camel_MoveSpit-->.UpdateCamelSpitFrame

Camel_MoveSpit-->.ExitMoveCamelSpit

Camel_MoveSpit-->Camel_SpitSoundSetFrequency

Camel_JumpToSpitSound-->Camel_SpitSound

Camel_SpitSelected-->Camel_SetSpitPosition

Camel_DisableSpitSprite-->Camel_DisableSpitNoise



1C57-->Camel_SpitSound

1C57-->.b1c9e

1C57<-->$1D29

1C57-->$1C30



Camel_EnableSpitSprite-->Camel_TestForSpitBomb


IRQ_CheckCamelFrameSound-->IRQ_ResetCamelAnimationFrame

IRQ_CheckCamelFrameSound-->.SetBackLegsFrame

Camel_SetSpitFrequency-->Camel_RandomiseSpit

Camel_SpitSoundSetFrequency-->Camel_SpitHomeOnShip

Camel_DisableSpitNoise-->Camel_DisableSpitNoiseB

Camel_SpitSound-->.MoveSpitSelectEnemy

1D1E-->$1C57


Camel_SpitHomeOnShip-->Player_ShipExplosion

Camel_SpitHomeOnShip-->Camel_DisableSpit

Player_DamageScreenFlash-->.DamageNoise


Player_ShipExplosion<-->Player_UpdateShipFrame

Player_ShipExplosion-->.NextLine

Player_ShipExplosion<-->Player_EnableExplosionSprites

Player_ShipExplosion-->Player_ExplosionEnded

Player_ShipExplosion-->.NextExplosionSprite

Player_ShipExplosion-->Player_DecreaseExplosionCounter



Player_DecreaseExplosionCounter-->.ExplosionX1Update

Player_DecreaseExplosionCounter-->Player_DisableExplosionSprites


InitLevel_InitialseGameVariables<-->Screen_DisplayStars

InitLevel_InitialseGameVariables<-->Screen_ClearBottomRows

InitLevel_InitialseGameVariables<-->Screen_DisplayCamelBonus

InitLevel_InitialseGameVariables<-->InitLevel_SetDifficulty

















InitLevel_InitialiseCamelStats-->InitLevel_InitialiseCamelColour







Score_Add1Point<-->Camel_DecreaseCamelHealth

Score_Add1Point-->Score_IncreaseScore

Score_AddBonusPoints<-->Score_IncreaseScore

Score_AddBonusPoints<-->Screen_DisplayCamelBonus

Screen_DisplayCamelBonus-->.IncreaseBonusCharLoop

Camel_CheckRemainingCamels-->Camel_ResetHeadSprite

Camel_CheckRemainingCamels-->Player_NextSector



Hyperdrive_EngageHyperdrive<-->Hyperdrive_ResetShipSpriteFrame

Hyperdrive_EngageHyperdrive<-->Player_UpdateShipSprite

Hyperdrive_EngageHyperdrive-->Hyperdrive_InitialiseLevel



Hyperdrive_InitialiseLevel<-->Hyperdrive_InitialiseRocket

Hyperdrive_InitialiseLevel<-->Hyperdrive_UpdatePlayer

Hyperdrive_InitialiseLevel<-->Hyperdrive_MoveLandscape

Hyperdrive_InitialiseLevel<-->Hyperdrive_MoveRocket

Hyperdrive_InitialiseLevel-->Player_ShipExplosion

Hyperdrive_InitialiseLevel-->.MainHyperdriveLoop

Hyperdrive_InitialiseLevel-->Hyperdrive_ClearRocketSprite

Hyperdrive_UpdatePlayer<-->Player_UpdateShipSprite

Hyperdrive_UpdatePlayer<-->Input_CheckJoy

Hyperdrive_MoveLandscape<-->Game_MoveLandscape

Hyperdrive_MoveLandscape-->Player_UpdateShipSprite


Hyperdrive_AnimateShip<-->Hyperdrive_DecreaseShipX

Hyperdrive_AnimateShip-->Hyperdrive_ClearRocketSprite

Hyperdrive_AnimateShip-->Hyperdrive_Jumping

Hyperdrive_DecreaseShipX<-->Game_MoveLandscape

Hyperdrive_DecreaseShipX-->Hyperdrive_MoveLandscape

Hyperdrive_Jumping<-->.LandscapeUpdate

Hyperdrive_Jumping-->Hyperdrive_ResetShipY

Hyperdrive_Jumping<-->Game_MoveLandscape

Hyperdrive_Finishing<-->.FlashShipSpriteColour

Hyperdrive_Finishing-->.ShipHyperdriveSoundLoop

Hyperdrive_Finishing-->.ExitHyperdriveFinishing

Hyperdrive_Finishing-->Player_UpdateShipSprite

Hyperdrive_Finishing-->Hyperdrive_Ended

Hyperdrive_InitialiseRocket-->Hyperdrive_InitialiseCounters

Hyperdrive_MoveRocket-->.SetRocketSpriteFrame



Hyperdrive_SetRocketHoming-->Hyperdrive_DecreaseCounter

Hyperdrive_ClearRocketSprite-->Hyperdrive_AnimateShip

Hyperdrive_ResetShipSpriteFrame-->Hyperdrive_ResetShipSprite




InitLevel_InitialisePlayerStats<-->InitLevel_InitialisePlayerStatsB

InitLevel_InitialisePlayerStats-->InitLevel_InitSprites

Player_LoseLife-->.Player2Selected

Player_LoseLife-->InitLevel_InitialseGameVariablesB

281F-->$05D0

281F-->.b2822

InitLevel_InitialseGameVariablesB<-->Init_StoreCamelsRemaining

InitLevel_InitialseGameVariablesB-->.CopyPlayerInitStats

InitLevel_InitialseGameVariablesB<-->Init_ReadCamelsRemaining

InitLevel_InitialseGameVariablesB<-->InitLevel_PrepareToStart

InitLevel_InitialisePlayerStatsD-->InitLevel_InitialiseCamelStats



Player_ExplosionEnded-->InitLevel_InitSprites

InitLevel_PrepareToStart-->Screen_DisplayCamelMarker


InitLevel_InitialisePlayerStatsB-->Sound_InitFrequency3

Screen_DisplayCamelMarker<-->.SetCamelMarkerScreenLo

Screen_DisplayCamelMarker<-->Screen_Plot

InitLevel_InitialisePlayerStatsC-->InitLevel_InitialisePlayerStatsD ;DONE

Screen_ClearBottomRows-->Player_CheckLives ;DONE

Player_NextSector-->Camel_ResetCamelPosition

Hyperdrive_Ended-->Hyperdrive_PrepareForNextSector

Camel_ResetCamelPosition<-->InitLevel_InitialiseCamelStats

Camel_ResetCamelPosition<-->Screen_DisplayCamelMarker

Camel_ResetCamelPosition-->Camel_ResetCamelsRemaining

Hyperdrive_PrepareForNextSector-->InitLevel_InitSprites

Camel_ResetCamelsRemaining-->Hyperdrive_EngageHyperdrive

InitLevel_SetDifficulty-->Screen_UpdatePlayerStats








Player_CheckLives-->Player_LoseLife

Player_CheckLives-->Score_CheckPlayerScores

Player_CheckLives-->.PrepareToStart

Player_CamelCollisionDetection-->Player_ShipExplosion


Menu_DisplayJMPresents<-->Screen_ClearScreen

Menu_DisplayJMPresents-->Menu_DisplayIntroScreen


Menu_DisplayIntroScreen-->Menu_OptionSelect



Menu_OptionsSelect-->Menu_SelectPlayers

Menu_OptionsSelect-->Menu_SelectSector

Menu_OptionsSelect-->Menu_SelectCollisions

Menu_OptionsSelect-->InitLevel_ResetSpriteIO

Menu_OptionsSelect-->Menu_OptionSelect

Menu_SelectPlayers-->.IntroWaitFire

Menu_SelectSector-->.IntroWaitKey ;DONE

Menu_SelectSector-->.UpdateSector ;DONE

Menu_SelectCollisions-->.IntroWaitKey ;DONE

Menu_SelectCollisions-->.IntroWaitKey ;DONE

InitLevel_ResetLives<-->InitLevel_CheckNumberOfPlayers ;DONE

InitLevel_ResetLives-->InitLevel_CheckSectorAndCollisions ;DONE


InitLevel_CheckSectorAndCollisions<-->Screen_ClearScreen

InitLevel_CheckSectorAndCollisions<-->Init_ScreenPointerArray 


InitLevel_ResetSpriteIO-->InitLevel_ResetLives


Score_CheckHiScore-->Score_CheckHiScoreB

Score_CheckPlayerScores<-->Score_CheckHiScore

Score_CheckPlayerScores<-->Score_CheckHiScore

Score_CheckPlayerScores-->Init_Restart


Game_CheckSectorDefences-->.DisplaySectorDefencesText

Game_CheckSectorDefences-->Game_ResetScreenColours


Game_ResetScreenColours-->Player_ShipExplosion

Sound_InitFrequency3-->InitLevel_InitialisePlayerStatsC

Hyperdrive_ResetShipY-->Hyperdrive_Finishing





